### PR TITLE
✨ Update `view_lineage()` to display graphs

### LINKED ISSUE #177: Get artifact$view_lineage() to work
Can you remind me, @lazappi, why this doesn't work in R? Doesn't in find the graphviz binary or similar? I'd have assumed the Python version would "just work".

What I'll do in the meantime is have `artifact.view_lineage()` _also_ print a https link to the hub so that people can just click on it. This means we shouldn't throw an error in LaminR more but simply let the Python function handle this.

Does this make sense?

### PR DESCRIPTION
**Pull request by lazappi**
**Related to:**
- Fixes #177
- Replaces #178 
- Requires https://github.com/laminlabs/lamindb/pull/2626

## Description

Updates the `view_lineage()` function to display a lineage graph from an object returned by Python. 

## Checklist

**Before review**

- [ ] Update and regenerate man pages
- [ ] Add/update tests
- [ ] Add/update examples in vignettes
- [x] Pass CI checks

**Before merge**

- [x] Update `CHANGELOG`

### CODE REVIEW

File: R/Artifact.R [hunk 1]
```diff
@@ -15,8 +15,10 @@ py_to_r.lamindb.models.artifact.Artifact <- function(x) { # nolint object_length
       open = function(mode = "r", is_run_input = NULL, ...) {
         artifact_open(self, mode = mode, is_run_input = is_run_input, ...)
       },
-      view_lineage = function(with_children = TRUE) {
-        view_lineage()
+      view_lineage = function(with_children = TRUE, return_graph = FALSE) {
```
Comment (falexwolf) [inline R/Artifact.R:18]: Why are you setting this to `False`? I thought the point was to take this and visualize it? 🤔

File: R/view.R [hunk 2]
```diff
@@ -1,6 +1,28 @@
-view_lineage <- function() {
-  cli::cli_alert_danger(paste(
-    "{.fun view_lineage} is not yet implemented.",
-    "Please view the lineage in the web interface."
-  ))
+view_lineage <- function(artifact, with_children = TRUE, return_graph = FALSE) {
+  py_artifact <- unwrap_python(artifact)
+
+  graph <- py_artifact$view_lineage(
+    with_children = with_children, return_graph = TRUE
```
Comment (falexwolf) [inline R/view.R:5]: I see! Great!

**Review by falexwolf — APPROVED** [review]
Great!

**Comment by falexwolf** [comment]
@lazappi, are the tests failing here because lamindb is not installed from the github main branch?

How can we install from github main? Shall we go through `install_lamindb()` or rather through reticulate?

@sunnyosun, can you please document the use of reticulate in the quickstart so that users have a better way to trouble shoot environment issues?

**Comment by lazappi** [comment]
> @lazappi, are the tests failing here because lamindb is not installed from the github main branch?

Yes, the extra argument I added is needed here but isn't in the latest `lamindb` release.
 
> How can we install from github main? Shall we go through `install_lamindb()` or rather through reticulate?

We could do something like this: https://github.com/laminlabs/laminr/blob/main/.github/workflows/test-unit.yaml#L78-L82
I'm not sure about testing against the GitHub version though. We might run into issues because the version we test against is different to what gets installed when people use the package.
 
> @sunnyosun, can you please document the use of reticulate in the quickstart so that users have a better way to trouble shoot environment issues?

I'm working on updating how the Python dependencies are managed which I hope will make things simpler. There will still need to be some setup instructions though for people who what to use their own environment.

**Comment by falexwolf** [comment]
Thanks, Luke!

> We might run into issues because the version we test against is different to what gets installed when people use the package.

We'll run against lamindb main in PRs and we'll run against lamindb release in dispatched integration tests. This is what we do for all our dependent repos.

**Comment by lazappi** [comment]
Ok. I think for the unit tests we are currently doing the opposite, testing against release `lamindb` most of the time and GitHub `lamindb` for dispatch runs. For the docs we always use the release. I'll make a separate PR for this.

**Comment by falexwolf** [comment]
@lazappi, let me do this because installing lamindb from github main is a bit more tricky than a regular package due to submodules.

I'll just add the logic we have everywhere else.

**Comment by lazappi** [comment]
I didn't have issues with it before but ok. The tests use their own environment so there is a `LAMIN_TEST_VERSION` environment variable that needs to be set to "devel" for them to install from GitHub. Although, if you think there are issues with this maybe it won't work...

I pushed something to the `update-ci` branch if it helps to see what I was going to do.

**Comment by falexwolf** [comment]
Oh, if you already started please finish it! I just wanted to offer help.

I think you might not have run into problems because there are very rarely breaking internal changes among the submodules.

But I can just look at what you're doing and then help fix it if necessary. ☺️ 

Please just make the PR you were planning on making! 🙏 -- Sorry for the confusion.

**Comment by rcannood** [comment]
I think that dot needs to be installed in the CI for this PR to work:

>  ! graphviz.backend.execute.ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

**Comment by lazappi** [comment]
> I think that dot needs to be installed in the CI for this PR to work:

Hmmm...that did work. I was waiting for #186 but I think there has been a `lamindb` release since then which adds the argument we need.

**Review by rcannood — APPROVED** [review]
LGTM!
